---
name: Deploy Watchtower

when:
  event:
    - push

steps:
  - name: git-pull
    image: alpine/git
    volumes:
      - /tank:/tank
    commands:
      - git config --global --add safe.directory /tank/docker/compose/watchtower
      - git -C /tank/docker/compose/watchtower pull origin main

  - name: render-env
    image: alpine
    volumes:
      - /tank:/tank
    environment:
      WATCHTOWER_HOSTNAME: raspberrypi
      WATCHTOWER_NOTIFICATIONS: email
      EMAIL_FROM:
        from_secret: EMAIL_FROM
      EMAIL_TO:
        from_secret: EMAIL_TO
      EMAIL_SERVER:
        from_secret: EMAIL_SERVER
      EMAIL_PORT:
        from_secret: EMAIL_PORT
      EMAIL_USER:
        from_secret: EMAIL_USER
      EMAIL_PASS:
        from_secret: EMAIL_PASS
    commands:
      # start fresh
      - rm -f /tank/docker/compose/watchtower/.env
      - echo "# Watchtower settings" \
          > /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_HOSTNAME=$WATCHTOWER_HOSTNAME" \
          >> /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_NOTIFICATIONS=$WATCHTOWER_NOTIFICATIONS" \
          >> /tank/docker/compose/watchtower/.env
      - echo "" \
          >> /tank/docker/compose/watchtower/.env
      - echo "# Email settings" \
          >> /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_NOTIFICATION_EMAIL_FROM=$EMAIL_FROM" \
          >> /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_NOTIFICATION_EMAIL_TO=$EMAIL_TO" \
          >> /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_NOTIFICATION_EMAIL_SERVER=$EMAIL_SERVER" \
          >> /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=$EMAIL_PORT" \
          >> /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=$EMAIL_USER" \
          >> /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=$EMAIL_PASS" \
          >> /tank/docker/compose/watchtower/.env
      - echo "" \
          >> /tank/docker/compose/watchtower/.env
      - echo "# Behavior" \
          >> /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_CLEANUP=true" \
          >> /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_INCLUDE_RESTARTING=true" \
          >> /tank/docker/compose/watchtower/.env
      - echo "WATCHTOWER_POLL_INTERVAL=86400" \
          >> /tank/docker/compose/watchtower/.env
      - chmod 600 /tank/docker/compose/watchtower/.env

  - name: restart-compose
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tank:/tank
    commands:
      - cd /tank/docker/compose/watchtower
      - docker compose down
      - docker compose up -d
