---
name: Deploy Watchtower

when:
  event:
    - push

steps:
  git-pull:
    image: alpine/git
    volumes:
      - /tank:/tank
    commands:
      - cd /tank/docker/compose/watchtower
      - git config --global --add safe.directory /tank/docker/compose/watchtower
      - git pull origin main

  render-env:
    image: alpine
    volumes:
      - /tank:/tank
    environment:
      EMAIL_FROM: from_secret
      EMAIL_TO: from_secret
      EMAIL_SERVER: from_secret
      EMAIL_PORT: from_secret
      EMAIL_USER: from_secret
      EMAIL_PASS: from_secret
    commands:
      - |
        cd /tank/docker/compose/watchtower
        export WATCHTOWER_HOSTNAME=${WATCHTOWER_HOSTNAME:-raspberrypi}
        export WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS:-email}
        export WATCHTOWER_NOTIFICATION_EMAIL_FROM="$EMAIL_FROM"
        export WATCHTOWER_NOTIFICATION_EMAIL_TO="$EMAIL_TO"
        export WATCHTOWER_NOTIFICATION_EMAIL_SERVER="$EMAIL_SERVER"
        export WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT="$EMAIL_PORT"
        export WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER="$EMAIL_USER"
        export WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD="$EMAIL_PASS"
        cat <<EOF > .env
# Watchtower settings
WATCHTOWER_HOSTNAME=${WATCHTOWER_HOSTNAME}
WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS}

# Email settings
WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_NOTIFICATION_EMAIL_FROM}
WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_NOTIFICATION_EMAIL_TO}
WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER}
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT}
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER}
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD}

# Behavior
WATCHTOWER_CLEANUP=true
WATCHTOWER_INCLUDE_RESTARTING=true
WATCHTOWER_POLL_INTERVAL=86400
EOF
    - chmod 600 .env


  restart-compose:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tank:/tank
    commands:
      - cd /tank/docker/compose/watchtower
      - docker compose down
      - docker compose up -d
