---
name: Deploy Watchtower

when:
  event:
    - push

clone:
  git:
    image: woodpeckerci/plugin-git
    depth: 1

steps:
  - name: git-pull
    image: alpine/git
    volumes:
      - /tank:/tank
    commands:
      - git config --global --add safe.directory /tank/docker/compose/watchtower
      - git -C /tank/docker/compose/watchtower pull origin main

  - name: debug-secrets
    image: alpine
    environment:
      EMAIL_FROM:
        from_secret: EMAIL_FROM
      EMAIL_TO:
        from_secret: EMAIL_TO
      EMAIL_SERVER:
        from_secret: EMAIL_SERVER
      EMAIL_PORT:
        from_secret: EMAIL_PORT
      EMAIL_USER:
        from_secret: EMAIL_USER
      EMAIL_PASS:
        from_secret: EMAIL_PASS
    commands:
      # List all EMAIL_* vars
      - echo "EMAIL_FROM   = ${EMAIL_FROM}"
      - echo "EMAIL_TO     = ${EMAIL_TO}"
      - echo "EMAIL_SERVER = ${EMAIL_SERVER}"
      - echo "EMAIL_PORT   = ${EMAIL_PORT}"
      - echo "EMAIL_USER   = ${EMAIL_USER}"
      - echo "EMAIL_PASS   = ${EMAIL_PASS}"
      # Or to see just the variable names and see that they're set (masked):
      - env | grep EMAIL_

  - name: render-env
    image: alpine
    volumes:
      - /tank:/tank
    environment:
      WATCHTOWER_HOSTNAME: raspberrypi
      WATCHTOWER_NOTIFICATIONS: email
      EMAIL_FROM:
        from_secret: EMAIL_FROM
      EMAIL_TO:
        from_secret: EMAIL_TO
      EMAIL_SERVER:
        from_secret: EMAIL_SERVER
      EMAIL_PORT:
        from_secret: EMAIL_PORT
      EMAIL_USER:
        from_secret: EMAIL_USER
      EMAIL_PASS:
        from_secret: EMAIL_PASS
    commands:
      - |
        cat <<EOF > /tank/docker/compose/watchtower/.env
        # Watchtower settings
        WATCHTOWER_HOSTNAME=${WATCHTOWER_HOSTNAME}
        WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS}

        # Email settings
        WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_FROM}
        WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAIL_TO}
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${EMAIL_SERVER}
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${EMAIL_PORT}
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAIL_USER}
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_PASS}

        # Behavior
        WATCHTOWER_CLEANUP=true
        WATCHTOWER_INCLUDE_RESTARTING=true
        WATCHTOWER_POLL_INTERVAL=86400
        EOF
      - chmod 600 /tank/docker/compose/watchtower/.env

  - name: restart-compose
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tank:/tank
    commands:
      - cd /tank/docker/compose/watchtower
      - docker compose down
      - docker compose up -d
