---
name: Deploy Watchtower

when:
  event:
    - push

clone:
  git:
    image: woodpeckerci/plugin-git
    depth: 1

steps:
  - name: git-pull
    image: alpine/git
    volumes:
      - /tank:/tank
    commands:
      - git config --global --add safe.directory /tank/docker/compose/watchtower
      - git -C /tank/docker/compose/watchtower pull origin main

  - name: render-env
    image: alpine
    volumes:
      - /tank:/tank
    environment:
      WATCHTOWER_HOSTNAME: raspberrypi
      WATCHTOWER_NOTIFICATIONS: email
      EMAIL_FROM:
        from_secret: EMAIL_FROM
      EMAIL_TO:
        from_secret: EMAIL_TO
      EMAIL_SERVER:
        from_secret: EMAIL_SERVER
      EMAIL_PORT:
        from_secret: EMAIL_PORT
      EMAIL_USER:
        from_secret: EMAIL_USER
      EMAIL_PASS:
        from_secret: EMAIL_PASS
    commands:
      - |
                #–– Debug: make sure secrets exist ––
        if [ -z "$EMAIL_FROM" ]; then
          echo "❌ EMAIL_FROM is empty"
          exit 1
        else
          # show masked length instead of the secret itself
          len=$(printf '%s' "$EMAIL_FROM" | wc -c)
          echo "✅ EMAIL_FROM injected (length=$len)"
        fi

        #–– Now render your .env ––
        cat > /tank/docker/compose/watchtower/.env <<EOF
        # Watchtower settings
        WATCHTOWER_HOSTNAME=${WATCHTOWER_HOSTNAME}
        WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS}

        # Email settings
        WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_FROM}
        WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAIL_TO}
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${EMAIL_SERVER}
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${EMAIL_PORT}
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAIL_USER}
        WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_PASS}

        # Behavior
        WATCHTOWER_CLEANUP=true
        WATCHTOWER_INCLUDE_RESTARTING=true
        WATCHTOWER_POLL_INTERVAL=86400
        EOF
      - chmod 600 /tank/docker/compose/watchtower/.env

  - name: restart-compose
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tank:/tank
    commands:
      - cd /tank/docker/compose/watchtower
      - docker compose down
      - docker compose up -d
